
package br.com.silbeckpro.hotelcontinentaljpa.gui;

import br.com.silbeckpro.hotelcontinentaljpa.Reserva;
import br.com.silbeckpro.hotelcontinentaljpa.persistencia.ReservasDAO;
import java.awt.Font;
import java.text.NumberFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Locale;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;


public class TelaCheckIn extends javax.swing.JFrame {
    private List<Reserva> listaCheckin;
  
    public TelaCheckIn(JTable tblCheckIn) {
        initComponents();
       
        //Código para definir o ícone
        ImageIcon logo = new ImageIcon(getClass().getResource("/Icons/Logo.png"));
        this.setIconImage(logo.getImage());
        
        carregarCheckIn();
    }
    
    //Método para carregar os Check-In
    private void carregarCheckIn() {
        ReservasDAO reservaDAO = new ReservasDAO();
        listaCheckin = reservaDAO.listarCheckIn();
        preencherCheckIn(listaCheckin);
    }
    
    //Método para preencher a tabela
    public void preencherCheckIn(List<Reserva> reservas) {
        if (reservas.isEmpty()) {
            LocalDate hoje = LocalDate.now();
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/y");
            String dataFormatada = hoje.format(formatter);
            
            JOptionPane.showMessageDialog(rootPane, "Não há reservas confirmadas para hoje '" 
                    + dataFormatada + "'!", "SEM RESERVAS", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String colunas[] = {"Id", "Nome", "Check-In", "Check-Out", "Quarto", "Total Dias", "Valor total", "Status"};
        String dados[][] = new String [reservas.size()][colunas.length];
        
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/y");
        NumberFormat formatoMoeda = NumberFormat.getCurrencyInstance(new Locale("pt", "BR"));
        
        int i = 0;
        for(Reserva r: reservas) {
            String totalFormatado = formatoMoeda.format(r.getValorTotal());
            
            dados[i] = new String[]{
                String.valueOf(r.getId()),
                r.getHospede().getNome(),
                r.getCheckin().format(formatter),
                r.getCheckout().format(formatter),
                r.getQuarto().getNumero(),
                String.valueOf(r.getTotalDias()),
                totalFormatado,
                r.getEstatus()
            };
            i++;
        }
        DefaultTableModel model = new DefaultTableModel(dados, colunas);
        tblCheckIn.setModel(model);
        
        //Configura a fonte do cabeçalho
        tblCheckIn.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        
        //Ajusta a largura das colunas
        tblCheckIn.getColumnModel().getColumn(0).setPreferredWidth(60);
        tblCheckIn.getColumnModel().getColumn(1).setPreferredWidth(250);
        tblCheckIn.getColumnModel().getColumn(2).setPreferredWidth(75);
        tblCheckIn.getColumnModel().getColumn(3).setPreferredWidth(75);
        tblCheckIn.getColumnModel().getColumn(4).setPreferredWidth(55);
        tblCheckIn.getColumnModel().getColumn(5).setPreferredWidth(60);
        tblCheckIn.getColumnModel().getColumn(6).setPreferredWidth(100);
        tblCheckIn.getColumnModel().getColumn(7).setPreferredWidth(85);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCheckIn = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnConfirmarCheckIn = new javax.swing.JButton();
        btbVoltarCheckIn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CHECK-IN");

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(1, 22, 45));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Check-In");

        jScrollPane1.setBackground(new java.awt.Color(102, 102, 102));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tblCheckIn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tblCheckIn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Hóspede", "Check-In", "Check-Out", "Quarto", "Total Dias", "Valor Total", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblCheckIn.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(tblCheckIn);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnConfirmarCheckIn.setBackground(new java.awt.Color(204, 204, 204));
        btnConfirmarCheckIn.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        btnConfirmarCheckIn.setForeground(new java.awt.Color(38, 115, 57));
        btnConfirmarCheckIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Confirmar.png"))); // NOI18N
        btnConfirmarCheckIn.setText("Confirmar");
        btnConfirmarCheckIn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnConfirmarCheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarCheckInActionPerformed(evt);
            }
        });

        btbVoltarCheckIn.setBackground(new java.awt.Color(204, 204, 204));
        btbVoltarCheckIn.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        btbVoltarCheckIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Sair_1.png"))); // NOI18N
        btbVoltarCheckIn.setText("Sair");
        btbVoltarCheckIn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btbVoltarCheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbVoltarCheckInActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(btbVoltarCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118)
                .addComponent(btnConfirmarCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(201, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmarCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btbVoltarCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(333, 333, 333)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 758, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btbVoltarCheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbVoltarCheckInActionPerformed
        dispose();
    }//GEN-LAST:event_btbVoltarCheckInActionPerformed

    private void btnConfirmarCheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarCheckInActionPerformed
        int linhaSelecionada = tblCheckIn.getSelectedRow();
        if (linhaSelecionada != - 1) {
            
            long reservaId = Long.parseLong((String) tblCheckIn.getValueAt(linhaSelecionada, 0));
            int resposta = JOptionPane.showConfirmDialog(rootPane, "Confirma Check-In?", "CHECK-IN", JOptionPane.YES_NO_OPTION);
            
            if (resposta == JOptionPane.YES_OPTION) {
                ReservasDAO reservaDAO = new ReservasDAO();
                reservaDAO.fazerCheckIn(reservaId);
                
                JOptionPane.showMessageDialog(rootPane, "Check-In realizado com sucesso!", "SUCESSO", JOptionPane.INFORMATION_MESSAGE);
                carregarCheckIn();
                
                if (listaCheckin.isEmpty()) {
                    dispose();
                } 
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Atenção: selecione a reserva para realizar o Check-In!", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnConfirmarCheckInActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        JTable tblCheckIn = new JTable();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCheckIn(tblCheckIn).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbVoltarCheckIn;
    private javax.swing.JButton btnConfirmarCheckIn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCheckIn;
    // End of variables declaration//GEN-END:variables
}
